name = "aiken-extra/auxlib"
version = "2.220.202412"
license = "Apache-2.0"
description = "An Aiken auxiliary library"

[repository]
user = "aiken-extra"
project = "auxlib"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.2.0"
source = "github"
