name = "aiken-extra/auxlib"
version = "2.190.202405"
license = "Apache-2.0"
description = "An Aiken auxiliary library"

[repository]
user = "aiken-extra"
project = "auxlib"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
